import RAPIER from '@dimforge/rapier3d-compat';
import {Moon,type Input} from './simulation/moon';
import {View} from './presentation/view';
import {Sound} from './platform/audio';
import {award,emptyProfile,readProfile,writeProfile,validateProfile,type Profile} from './platform/save';
import {DEFAULT_BINDINGS,RESOURCES,STEP} from './content/config';
import {clamp} from './core/rules';
import './ui/style.css';

const root=document.querySelector<HTMLDivElement>('#app')!,canvas=document.querySelector<HTMLCanvasElement>('#scene')!;
type Settings={sensitivity:number;fov:number;volume:number;text:number;invert:boolean;low:boolean;sprintToggle:boolean;toolToggle:boolean;bindings:Record<string,string>};
const defaults:Settings={sensitivity:1,fov:70,volume:.35,text:100,invert:false,low:false,sprintToggle:false,toolToggle:false,bindings:{...DEFAULT_BINDINGS,tool:'Mouse0'}};
let settings:Settings={...defaults,bindings:{...defaults.bindings}};
try{const raw=JSON.parse(localStorage.getItem('moon-goons-settings')||'null');if(raw){settings={...defaults,...raw,bindings:{...defaults.bindings,...raw.bindings}};settings.fov=clamp(Number(settings.fov)||70,55,90);settings.sensitivity=clamp(Number(settings.sensitivity)||1,.2,2.5);settings.text=clamp(Number(settings.text)||100,100,150);settings.volume=clamp(Number(settings.volume)||0,0,1);}}catch{}
let profile=emptyProfile(),storageBlocked=false,saveMessage='',moon:Moon,view:View;
let mode:'intro'|'play'|'results'='intro',paused=false,panel='',yaw=0,pitch=.25,activeTool=1,previousTime=0,accumulator=0,toastUntil=0,drillSound=0,finishDelay=0;
let sprintOn=false,toolOn=false,rebind:string|null=null,pendingImport:Profile|null=null,pointerUnavailable=false;
let qaReplay=false,qaStage=0,qaTicks=0;
const keys=new Set<string>(),pressed=new Set<string>(),sound=new Sound();
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
function keyName(code:string){return code.replace('Key','').replace('Digit','').replace('Left','').replace('Mouse0','LMB').replace('Space','SPACE');}
function toast(text:string){el('toast').textContent=text;el('toast').classList.add('show');toastUntil=performance.now()+4200;}
function clearInput(){keys.clear();pressed.clear();toolOn=false;sprintOn=false;}
function applySettings(){sound.volume=settings.volume;view?.quality(settings.low);document.documentElement.style.setProperty('--text-scale',String(settings.text/100));try{localStorage.setItem('moon-goons-settings',JSON.stringify(settings));}catch{} }
function lock(){sound.unlock();if(mode==='play'&&!paused&&!pointerUnavailable){canvas.requestPointerLock()?.catch(()=>{pointerUnavailable=true;toast('Right-drag the scene to look around, or use the arrow keys.');});}}
function openPanel(name:string){clearInput();panel=name;paused=mode==='play';document.exitPointerLock();el('modal-layer').hidden=false;el('modal-layer').innerHTML='';if(name==='settings')renderSettings();else if(name==='help')renderHelp();else if(name==='leave')renderLeave();else renderPause();}
function closePanel(){panel='';el('modal-layer').hidden=true;el('modal-layer').innerHTML='';paused=false;clearInput();if(mode==='play')lock();}
function modal(title:string,body:string){el('modal-layer').innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="${title}"><div class="modal-head"><h2>${title}</h2><button class="icon-button" id="close-modal" aria-label="Close">×</button></div>${body}</section>`;el('close-modal').onclick=closePanel;el('close-modal').focus();}
function renderSettings(){
  const names:Record<string,string>={forward:'Move forward',back:'Move backward',left:'Move left',right:'Move right',jump:'Jump',sprint:'Sprint',grab:'Grab / release',burst:'Suit burst',scan:'Quick scan',tool:'Use tool'};
  modal('Make yourself comfortable',`<p class="muted">Settings are saved on this browser. The mission is paused.</p><div class="setting-grid"><label>Look sensitivity <output id="sens-out">${settings.sensitivity.toFixed(1)}</output><input id="sensitivity" type="range" min=".2" max="2.5" step=".1" value="${settings.sensitivity}"></label><label>Field of view <output id="fov-out">${settings.fov}°</output><input id="fov" type="range" min="55" max="90" value="${settings.fov}"></label><label>Sound effects <output id="vol-out">${Math.round(settings.volume*100)}%</output><input id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label><label>Text size <output id="text-out">${settings.text}%</output><input id="text" type="range" min="100" max="150" step="10" value="${settings.text}"></label></div><div class="switches">${(['invert','low','sprintToggle','toolToggle'] as const).map((k,i)=>`<label><input id="${k}" type="checkbox" ${settings[k]?'checked':''}>${['Invert vertical look','Low graphics · fewer shadows','Toggle sprint','Toggle tool use'][i]}</label>`).join('')}</div><h3>Keyboard & mouse</h3><p class="muted small">Select a binding, then press a key. Escape cancels. Left click can be restored with Reset controls.</p><div class="bindings">${Object.entries(names).map(([k,v])=>`<button data-bind="${k}"><span>${v}</span><kbd>${keyName(settings.bindings[k])}</kbd></button>`).join('')}</div><button class="text-button" id="reset-controls">Reset controls</button><div class="save-tools"><h3>Your research file</h3><p class="muted">${profile.credits} credits · ${profile.rp} research · ${profile.runs} completed sorties</p><p class="muted small">Export a backup before changing computers or clearing browser data.</p><div class="button-row"><button class="secondary" id="export-save">Export backup</button><button class="secondary" id="import-save">Import backup</button><button class="text-button" id="restore-backup">Restore previous save</button></div><input id="save-file" type="file" accept=".json,application/json" hidden><p id="save-note" class="small">${saveMessage}</p></div>`);
  for(const [id,output,suffix] of [['sensitivity','sens-out',''],['fov','fov-out','°'],['volume','vol-out','%'],['text','text-out','%']])el<HTMLInputElement>(id).oninput=()=>{const value=Number(el<HTMLInputElement>(id).value);(settings as unknown as Record<string,unknown>)[id]=value;el(output).textContent=(id==='volume'?Math.round(value*100):value)+suffix;applySettings();};
  for(const id of ['invert','low','sprintToggle','toolToggle'] as const)el<HTMLInputElement>(id).onchange=()=>{settings[id]=el<HTMLInputElement>(id).checked;applySettings();};
  document.querySelectorAll<HTMLButtonElement>('[data-bind]').forEach(b=>b.onclick=()=>{rebind=b.dataset.bind!;b.querySelector('kbd')!.textContent='PRESS KEY';});
  el('reset-controls').onclick=()=>{settings.bindings={...defaults.bindings};applySettings();renderSettings();};
  el('export-save').onclick=exportSave;el('import-save').onclick=()=>el<HTMLInputElement>('save-file').click();
  el<HTMLInputElement>('save-file').onchange=async()=>{try{const f=el<HTMLInputElement>('save-file').files?.[0];if(!f)return;if(f.size>1000000)throw new Error('Save files must be smaller than 1 MB.');pendingImport=validateProfile(JSON.parse(await f.text()));renderImport();}catch(e){el('save-note').textContent=(e as Error).message;}};
  el('restore-backup').onclick=async()=>{try{pendingImport=await readProfile(true);renderImport();}catch(e){el('save-note').textContent=(e as Error).message;}};
}
function exportSave(){const b=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='MoonGoons-research-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderImport(){if(!pendingImport)return;modal('Replace this research file?',`<p>The selected backup contains <strong>${pendingImport.credits} credits, ${pendingImport.rp} research, and ${pendingImport.runs} sorties</strong>.</p><p>This will replace the current profile. Export your current progress first if you want to keep both.</p><div class="button-row"><button id="confirm-import" class="primary">Replace profile</button><button id="cancel-import" class="secondary">Keep current profile</button></div>`);el('confirm-import').onclick=async()=>{try{await writeProfile(pendingImport!);profile=pendingImport!;pendingImport=null;storageBlocked=false;saveMessage='Backup restored.';renderSettings();updateProfile();}catch(e){toast((e as Error).message);}};el('cancel-import').onclick=renderSettings;}
function renderHelp(){modal('A very brief safety briefing',`<div class="help-steps"><article><span>01</span><div><h3>Find something worth keeping.</h3><p>Walk toward the orange ore just left of your landing position. Press <kbd>${keyName(settings.bindings.scan)}</kbd> to reveal samples within 12 metres.</p></div></article><article><span>02</span><div><h3>Make the rock a smaller problem.</h3><p>Face a deposit and hold <kbd>${keyName(settings.bindings.tool)}</kbd> to drill. Let go when the heat gauge gets high. Switch tools with <kbd>1</kbd> and <kbd>2</kbd>.</p></div></article><article><span>03</span><div><h3>Bring your bad idea home.</h3><p>Press <kbd>${keyName(settings.bindings.grab)}</kbd> to carry the freed sample. Move into the striped ship bay, release it, and let it settle. Only secured cargo pays.</p></div></article></div><p class="muted">Move: WASD (or your bindings) · Look: mouse or arrow keys · Jump: ${keyName(settings.bindings.jump)} · Sprint: ${keyName(settings.bindings.sprint)} · Emergency burst: ${keyName(settings.bindings.burst)} · Brace: right mouse · Escape: pause.</p><p class="muted">This first field trip is solo. Online co-op is a later milestone. Practice has no timer and does not award permanent progress.</p><button class="primary wide" id="help-done">Got it. Probably.</button>`);el('help-done').onclick=closePanel;}
function renderPause(){modal('Taking a breather',`<p class="muted">Your mission is paused. Even S.P.A.C.E. allows that.</p><div class="stack"><button class="primary" id="resume">Back to the moon</button><button class="secondary" id="pause-settings">Settings & save backup</button><button class="secondary" id="pause-help">Controls & field guide</button><button class="text-button" id="recall">Recall suit to landing pad</button><button class="text-button" id="abandon">End this field trip</button></div>`);el('resume').onclick=closePanel;el('pause-settings').onclick=()=>openPanel('settings');el('pause-help').onclick=()=>openPanel('help');el('recall').onclick=()=>{moon.recall();closePanel();};el('abandon').onclick=()=>openPanel('leave');}
function renderLeave(){modal('Call it a day?',`<p>Your ${moon.manifest.length} secured samples are safe. Loose cargo will be left behind.</p><p class="muted">${moon.practice?'Practice does not award permanent credits or research.':'You will receive credits and research for everything already secured.'}</p><div class="button-row"><button class="primary" id="depart-now">Extract now</button><button class="secondary" id="stay">Stay on the moon</button></div>`);el('depart-now').onclick=()=>{closePanel();moon.finish();};el('stay').onclick=closePanel;}
function updateProfile(){el('profile-credits').textContent=String(profile.credits);el('profile-rp').textContent=String(profile.rp);}
function buildUI(){root.innerHTML=`
<div class="vignette"></div><header class="topbar"><a class="brand" href="#" id="brand-home" aria-label="Moon Goons menu"><span class="brand-mark">MG</span><span>MOON GOONS<small>S.P.A.C.E. FIELD OPERATIONS</small></span></a><div class="top-actions"><span class="build-tag">SOLO FIELD TEST <i></i> 0.2</span><button class="icon-button" id="help" aria-label="Field guide">?</button><button class="icon-button" id="settings" aria-label="Settings">⚙</button></div></header>
<section id="intro" class="intro"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> NOW RECRUITING • NO EXPERIENCE NECESSARY</div><h1>SMALL MOON.<br>BIG <span>PROBLEMS.</span></h1><p class="hero-description">Precious samples. Questionable equipment.<br>A perfectly reasonable amount of gravity.</p><div class="hero-actions"><button class="primary launch" id="start">Start field trip <span>↗</span></button><button class="practice-button" id="practice">Just bounce around <span>UNTIMED PRACTICE</span></button></div><div class="mission-facts"><span><b>05:00</b> UNTIL DEPARTURE</span><span><b>01</b> SCIENTIST</span><span><b>03</b> SAMPLE TYPES</span></div></div><aside class="destination-card"><div class="eyebrow">YOUR FIRST ASSIGNMENT <span>001</span></div><div class="destination-title"><span class="moon-icon">◒</span><div><h2>Practice Moon</h2><p>LUNAR SURVEY / OUTER SECTOR</p></div></div><div class="card-rule"></div><div class="destination-facts"><span>GRAVITY<strong>Low & floaty</strong></span><span>FORECAST<strong>Mostly survivable</strong></span></div><p class="mission-objective">Harvest samples. Haul them to the ship.<br>Leave before the company stops paying.</p><div class="card-footer"><span class="status-dot"></span> LANDING ZONE CLEARED</div></aside><footer class="intro-footer"><span>SCIENTIFIC PROCUREMENT & COLLECTION ENTERPRISE</span><span>Your research file <b id="profile-credits">0</b> CR <b id="profile-rp">0</b> RP</span></footer></section>
<section id="hud" hidden><div class="mission-strip"><div class="location-tag"><span class="eyebrow">FIELD TRIP 001</span><strong>Practice Moon</strong><span id="practice-tag">GRAVITY 3.0 m/s²</span></div><div id="clock-box" class="clock"><span id="clock-label">AUTO-DEPARTURE</span><strong id="clock">05:00</strong><span id="clock-bottom">Make the trip count.</span></div><div class="haul"><span class="eyebrow">SECURED CARGO</span><strong><span id="haul-credit">0</span><small> CR</small></strong><div class="capacity"><i id="capacity-bar"></i></div><span id="capacity">0 / 40 volume</span></div></div><div id="markers"></div><div id="reticle"><i></i></div><aside class="field-note"><span class="eyebrow" id="objective-step">YOUR FIRST HAUL</span><p id="objective">Find the orange ore near the landing pad.</p><div class="note-line"></div><span id="ship-distance">SHIP · 16 m</span><button id="return-button" class="text-button">Return / extract ↗</button></aside><div class="radar-wrap"><canvas id="radar" width="140" height="140" aria-label="Local survey map"></canvas><span>NORTH ↑ · 60 m</span></div><div id="interaction" class="interaction" hidden><div class="sample-title"><span id="sample-kind"></span><span id="sample-mass"></span></div><strong id="sample-name"></strong><p id="sample-action"></p><div class="progress-track"><i id="sample-progress"></i></div></div><div class="bottom-bar"><div class="tool-belt"><button id="tool-drill" class="tool selected"><kbd>1</kbd><span>UTILITY DRILL<small id="drill-state">Ready for questionable science</small></span></button><button id="tool-scan" class="tool"><kbd>2</kbd><span>SCANNER<small id="scan-state">Survey nearby samples</small></span></button></div><div class="suit-state"><span>SUIT BURST</span><div id="charges">● ●</div><small id="charge-hint">Q to recover</small></div></div><div id="heat-wrap" class="heat-wrap"><span id="heat-text">DRILL HEAT</span><div><i id="heat-bar"></i></div></div><div id="mouse-hint">Click the moon to look around · Esc pauses</div></section>
<div id="toast" role="status" aria-live="polite"></div><section id="results" hidden></section><div id="modal-layer" hidden></div>`;
  el('start').onclick=()=>start(false);el('practice').onclick=()=>start(true);el('settings').onclick=()=>openPanel('settings');el('help').onclick=()=>openPanel('help');el('brand-home').onclick=e=>{e.preventDefault();if(mode==='play')openPanel('pause');else if(mode==='results')home();};el('return-button').onclick=()=>openPanel('leave');el('tool-drill').onclick=()=>{activeTool=1;toolOn=false;lock();};el('tool-scan').onclick=()=>{activeTool=2;toolOn=false;lock();};updateProfile();
}
function start(practice:boolean){moon.dispose();moon=new Moon();moon.start(practice);view.reset(moon);mode='play';paused=false;panel='';yaw=0;pitch=.25;activeTool=1;finishDelay=0;accumulator=0;clearInput();el('intro').hidden=true;el('results').hidden=true;el('hud').hidden=false;el('modal-layer').hidden=true;el('practice-tag').textContent=practice?'UNTIMED TRAINING · NO REWARDS':'GRAVITY 3.0 m/s²';lock();toast(practice?'Practice makes adequate. Try scanning, drilling, and banking one sample.':'Welcome to Practice Moon. The orange ore is just to your left.');}
function home(){mode='intro';paused=false;panel='';el('intro').hidden=false;el('results').hidden=true;el('hud').hidden=true;el('modal-layer').hidden=true;updateProfile();}
async function finish(){mode='results';document.exitPointerLock();clearInput();el('hud').hidden=true;const aboard=moon.nearShip;let saveStatus=moon.practice?'Practice complete · permanent progress unchanged.':'Saving research file…';
  el('results').hidden=false;el('results').innerHTML=`<div class="result-card"><span class="eyebrow">S.P.A.C.E. POST-MISSION REPORT</span><div class="result-stamp">${moon.manifest.length?'✓':'↗'}</div><h1>${moon.practice?'FIELD TRAINING.':moon.manifest.length?'A FINE DAY<br>FOR SCIENCE.':'VALUABLE<br>EXPERIENCE.'}</h1><p class="muted">${moon.practice?'No overtime. No pressure. Slightly more qualified.':aboard?'Scientist aboard. The paperwork can wait.':'Suit retrieved. Next time, try boarding before departure.'}</p><div class="result-stats"><div><span>SECURED VALUE</span><strong>${moon.credits}<small> CR</small></strong></div><div><span>RESEARCH</span><strong>${moon.rp}<small> RP</small></strong></div><div><span>SAMPLES</span><strong>${moon.manifest.length}<small> / 10</small></strong></div></div><div class="manifest">${moon.manifest.length?moon.manifest.map(e=>`<div><span class="sample-dot" style="background:${RESOURCES[e.kind].hex}"></span><span>${RESOURCES[e.kind].label}<small>${Math.round(e.condition*100)}% condition</small></span><strong>${e.credits} CR</strong></div>`).join(''):'<p>No samples secured. Drop freed cargo inside the striped bay and let it settle before leaving.</p>'}</div><div class="run-facts"><span>${Math.round(moon.airTime)}s airborne</span><span>${Math.round(moon.walkDistance)}m travelled</span><span>${moon.lost} samples lost</span></div><p id="result-save" class="small">${saveStatus}</p><p class="muted small">Research unlocks and online co-op are coming in later milestones.</p><div class="button-row"><button class="primary" id="again">One more field trip ↗</button><button class="secondary" id="back-home">Back to landing</button><button class="text-button" id="result-export">Export progress</button><button class="text-button" id="retry-save" hidden>Retry save</button></div></div>`;
  el('again').onclick=()=>start(moon.practice);el('back-home').onclick=home;el('result-export').onclick=exportSave;
  if(!moon.practice){profile=award(profile,moon.runId,moon.credits,moon.rp,moon.manifest.filter(e=>e.condition>=.5).map(e=>e.kind));await persistResult();}el('again').focus();
}
async function persistResult(){try{if(storageBlocked)throw new Error('Existing save needs recovery. Export this progress, then open Settings.');await writeProfile(profile);saveMessage='Research file saved on this browser.';el('result-save').textContent=saveMessage;el('retry-save').hidden=true;}catch(e){saveMessage=(e as Error).message;el('result-save').textContent=saveMessage;el('retry-save').hidden=false;el('retry-save').onclick=persistResult;}}
function heldAction(action:string){return keys.has(settings.bindings[action]);}
function tap(action:string){return pressed.has(settings.bindings[action]);}
function input():Input{
  const result:Input={x:(heldAction('right')?1:0)-(heldAction('left')?1:0),z:(heldAction('forward')?1:0)-(heldAction('back')?1:0),yaw,jump:tap('jump'),burst:tap('burst'),grab:tap('grab'),scan:tap('scan')||(activeTool===2&&(settings.toolToggle?toolOn:heldAction('tool'))),use:activeTool===1&&(settings.toolToggle?toolOn:heldAction('tool')),sprint:settings.sprintToggle?sprintOn:heldAction('sprint'),brace:keys.has('Mouse2')};
  if(import.meta.env.DEV&&qaReplay){
    const p=moon.player.translation(),s=moon.samples[0];qaTicks++;
    const go=(x:number,z:number,tolerance:number)=>{yaw=Math.atan2(x-p.x,-(z-p.z));result.yaw=yaw;if(Math.hypot(x-p.x,z-p.z)>tolerance){result.z=1;return false;}return true;};
    if(qaStage===0){if(qaTicks===1)result.scan=true;if(go(-6,17,1.9)){qaStage=1;qaTicks=0;}}
    else if(qaStage===1){result.use=!moon.locked&&!moon.needsRelease;if(s.state==='loose'){qaStage=2;qaTicks=0;}}
    else if(qaStage===2&&qaTicks>80){result.grab=true;qaStage=3;qaTicks=0;}
    else if(qaStage===3){if(go(0,10,.35)){qaStage=4;qaTicks=0;}}
    else if(qaStage===4){if(go(0,1,.35)){qaStage=5;qaTicks=0;}}
    else if(qaStage===5){yaw=0;result.yaw=0;if(qaTicks>100){result.grab=true;qaStage=6;qaTicks=0;}}
    else if(qaStage===6&&moon.manifest.length>0&&qaTicks>120){moon.finish();qaReplay=false;}
  }
  return result;
}
function hud(){
  const seconds=Math.ceil(moon.remaining),minutes=Math.floor(seconds/60);el('clock').textContent=moon.practice?'∞':`${String(minutes).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;el('clock-label').textContent=moon.practice?'UNTIMED PRACTICE':'AUTO-DEPARTURE';el('clock-bottom').textContent=!moon.practice&&seconds<=60?'Return to the ship.':'Make the trip count.';el('clock-box').classList.toggle('urgent',!moon.practice&&seconds<=60);
  el('haul-credit').textContent=String(moon.credits);el('capacity').textContent=`${moon.volume} / 40 volume`;el('capacity-bar').style.width=`${moon.volume/40*100}%`;
  el('heat-bar').style.width=`${moon.heat}%`;el('heat-wrap').classList.toggle('hot',moon.locked||moon.heat>=75);el('heat-text').textContent=moon.locked?'OVERHEATED · RELEASE TO COOL':'DRILL HEAT';el('heat-wrap').hidden=activeTool!==1;
  el('drill-state').textContent=moon.locked?'Cooling down…':moon.held?'Release cargo to drill':moon.drilling?'Extracting sample…':'Ready for questionable science';el('scan-state').textContent=moon.scanWindup>0?'Scanning…':moon.scanCooldown>0?`Recharging · ${Math.ceil(moon.scanCooldown)}s`:'Survey nearby samples';
  el('tool-drill').classList.toggle('selected',activeTool===1);el('tool-scan').classList.toggle('selected',activeTool===2);el('charges').textContent=(moon.charges>=1?'●':'○')+' '+(moon.charges>=2?'●':'○');el('charge-hint').textContent=moon.charges<2?`Grounded recharge · ${Math.ceil(8-moon.recharge)}s`:`${keyName(settings.bindings.burst)} to recover`;
  const p=moon.player.translation(),shipD=Math.hypot(p.x,p.z);el('ship-distance').textContent=`SHIP · ${Math.round(shipD)} m ${moon.nearShip?'· CARGO BAY OPEN':''}`;
  let objective='Find the orange ore near the landing pad.';if(moon.manifest.length)objective='Cargo secured. Go for another sample, or extract early.';else if(moon.held)objective='Carry it into the striped bay. Release it and let it settle.';else if(moon.samples.some(s=>s.state==='loose'))objective='Grab the freed sample and bring it back to the ship.';else if(moon.target)objective='Hold your tool action to drill. Watch the heat gauge.';else if(moon.usedScan)objective='Follow a sample marker. Get close and face the deposit.';el('objective').textContent=objective;
  const target=moon.held||moon.target;el('interaction').hidden=!target;if(target){const c=RESOURCES[target.kind];el('sample-kind').textContent=c.category;el('sample-kind').style.color=c.hex;el('sample-name').textContent=c.label;el('sample-mass').textContent=`${c.mass} kg · ${c.volume} vol · ${Math.floor(c.credits*target.condition)} CR`;
    el('sample-action').textContent=moon.held?`${keyName(settings.bindings.grab)} release · ${Math.round(target.condition*100)}% condition`:target.state==='loose'?`${keyName(settings.bindings.grab)} grab · Bring it to the striped bay`:activeTool===2?`Scan complete · Press 1 to equip drill`:`${keyName(settings.bindings.tool)} hold to extract · ${Math.round(target.progress/c.seconds*100)}%`;
    el('sample-progress').style.width=`${target.state==='deposit'?target.progress/c.seconds*100:moon.held?target.condition*100:0}%`;}
  el('mouse-hint').hidden=document.pointerLockElement===canvas||paused;
  const markers:string[]=[];for(const s of moon.samples){if(s.state!=='deposit'&&s.state!=='loose')continue;const sp=s.body.translation();if(moon.scanReveal<=0&&moon.target!==s&&s!==moon.held)continue;if(Math.hypot(sp.x-p.x,sp.z-p.z)>12)continue;const position=view.project({x:sp.x,y:sp.y+1.3,z:sp.z});if(position.visible)markers.push(`<div class="world-marker" style="left:${position.x}px;top:${position.y}px;color:${RESOURCES[s.kind].hex}">◆<span>${RESOURCES[s.kind].label}</span></div>`);}el('markers').innerHTML=markers.join('');
  const ctx=el<HTMLCanvasElement>('radar').getContext('2d')!;ctx.clearRect(0,0,140,140);ctx.fillStyle='rgba(14,29,41,.66)';ctx.beginPath();ctx.arc(70,70,66,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#8dabb533';for(const r of [22,44,65]){ctx.beginPath();ctx.arc(70,70,r,0,Math.PI*2);ctx.stroke();}ctx.strokeStyle='#8dabb533';ctx.beginPath();ctx.moveTo(5,70);ctx.lineTo(135,70);ctx.moveTo(70,5);ctx.lineTo(70,135);ctx.stroke();ctx.fillStyle='#edcd78';ctx.fillRect(66,66,8,8);
  if(moon.scanReveal>0)for(const s of moon.samples){if(s.state!=='loose'&&s.state!=='deposit')continue;const sp=s.body.translation();if(Math.hypot(sp.x-p.x,sp.z-p.z)>12)continue;ctx.fillStyle=RESOURCES[s.kind].hex;ctx.beginPath();ctx.arc(70+sp.x,70+sp.z,3,0,7);ctx.fill();}ctx.save();ctx.translate(70+p.x,70+p.z);ctx.rotate(yaw);ctx.fillStyle='#e4eee4';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-4,4);ctx.lineTo(4,4);ctx.closePath();ctx.fill();ctx.restore();
}
let dragging=false;
function bindEvents(){
  window.addEventListener('keydown',e=>{
    if(rebind){e.preventDefault();if(e.code!=='Escape'){if(['Escape','Digit1','Digit2','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Tab'].includes(e.code)){toast('That key is reserved for menus, tools, or looking. Choose another.');return;}const conflict=Object.entries(settings.bindings).find(([k,v])=>k!==rebind&&v===e.code);if(conflict){toast(`That key already controls ${conflict[0]}. Choose another.`);return;}settings.bindings[rebind]=e.code;applySettings();}rebind=null;renderSettings();return;}
    if(e.code==='Escape'){e.preventDefault();if(panel)closePanel();else if(mode==='play')openPanel('pause');return;}
    if(panel){if(e.code==='Tab'){const focusables=el('modal-layer').querySelectorAll<HTMLElement>('button,input:not([hidden])');const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}
    if(mode!=='play'||paused)return;
    if(Object.values(settings.bindings).includes(e.code)||e.code.startsWith('Arrow'))e.preventDefault();
    if(!keys.has(e.code)){pressed.add(e.code);if(e.code===settings.bindings.sprint)sprintOn=!sprintOn;if(e.code===settings.bindings.tool)toolOn=!toolOn;}keys.add(e.code);if(e.code==='Digit1'){activeTool=1;toolOn=false;}if(e.code==='Digit2'){activeTool=2;toolOn=false;}
  });window.addEventListener('keyup',e=>keys.delete(e.code));
  canvas.addEventListener('mousedown',e=>{if(mode!=='play'||paused)return;dragging=e.button===2;if(document.pointerLockElement!==canvas)lock();const code=`Mouse${e.button}`;if(!keys.has(code)){pressed.add(code);if(code===settings.bindings.tool)toolOn=!toolOn;}keys.add(code);});
  window.addEventListener('mouseup',e=>{keys.delete(`Mouse${e.button}`);dragging=false;});
  window.addEventListener('mousemove',e=>{if(mode!=='play'||paused)return;if(document.pointerLockElement===canvas||dragging){yaw+=e.movementX*.0025*settings.sensitivity;pitch=clamp(pitch+e.movementY*.002*(settings.invert?-1:1)*settings.sensitivity,-.6,1.1);}});
  canvas.addEventListener('contextmenu',e=>e.preventDefault());
  canvas.addEventListener('wheel',e=>{if(mode==='play'&&!paused){activeTool=activeTool===1?2:1;toolOn=false;e.preventDefault();}},{passive:false});
  document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas)clearInput();});
  window.addEventListener('blur',()=>{clearInput();if(mode==='play'&&!paused)openPanel('pause');});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play'&&!paused)openPanel('pause');});
}
function frame(now:number){const dt=Math.min(.08,Math.max(0,(now-previousTime)/1000));previousTime=now;
  if(mode==='play'&&!paused){yaw+=((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*dt*1.6;pitch=clamp(pitch+((keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0))*dt,-.6,1.1);accumulator+=dt;let ticks=0;while(accumulator>=STEP&&ticks<5){moon.step(input());pressed.clear();accumulator-=STEP;ticks++;}if(ticks===5)accumulator=0;
    for(const e of moon.events.splice(0)){if(e.text)toast(e.text);if(e.type==='scan'){view.scanAt(moon);sound.play('scan');}if(['jump','grab','heat','bank','warning'].includes(e.type))sound.play(e.type as 'jump');if(e.type==='finish')finishDelay=3;}
    if(moon.drilling){drillSound-=dt;if(drillSound<=0){sound.play('drill');drillSound=.15;}}
    if(moon.finished&&finishDelay>0){finishDelay-=dt;el('clock-label').textContent='LIFT-OFF';if(finishDelay<=0)void finish();}
  }
  view.update(moon,dt,yaw,pitch,mode==='intro'||mode==='results',settings.fov);if(mode==='play')hud();if(now>toastUntil)el('toast').classList.remove('show');requestAnimationFrame(frame);
}
async function boot(){try{await RAPIER.init();try{profile=await readProfile();}catch(e){storageBlocked=true;saveMessage=(e as Error).message;}view=new View(canvas);moon=new Moon();view.reset(moon);buildUI();applySettings();bindEvents();if(storageBlocked)toast(saveMessage);requestAnimationFrame(frame);
  // Development-only observability for reproducible physics and browser checks.
  if(import.meta.env.DEV){(window as unknown as Record<string,unknown>).__moonTest={snapshot:()=>({mode,paused,remaining:moon.remaining,heat:moon.heat,locked:moon.locked,position:moon.player.translation(),yaw,target:moon.target?.id,held:moon.held?.id,manifest:moon.manifest,profile,samples:moon.samples.map(s=>({id:s.id,kind:s.kind,state:s.state,progress:s.progress,condition:s.condition,position:['deposit','loose'].includes(s.state)?s.body.translation():null}))})};
    if(new URLSearchParams(location.search).has('qa')){const button=document.createElement('button');button.id='qa-route';button.textContent='Run automated harvest route';button.style.cssText='position:fixed;bottom:4px;left:45%;z-index:99;font-size:10px;padding:6px;background:#f2cb79;pointer-events:auto';button.onclick=()=>{start(false);qaReplay=true;qaStage=0;qaTicks=0;};document.body.append(button);}
  }
}catch(e){root.innerHTML=`<section class="compatibility"><span class="brand-mark">MG</span><h1>The ship could not start.</h1><p>Moon Goons needs a desktop browser with WebGL 2 enabled. Try an updated Chrome, Edge, or Firefox with hardware acceleration.</p><p id="boot-error"></p><button onclick="location.reload()" class="primary">Try again</button></section>`;el('boot-error').textContent=(e as Error).message;console.error(e);}}
void boot();
